export const MIN_THREAD_TITLE = 8;
export const MAX_THREAD_TITLE = 64;
export const MIN_THREAD_CONTENT = 20;
export const MAX_THREAD_CONTENT = 8192;
export const MIN_FIRSTNAME = 2;
export const MAX_FIRSTNAME = 12;
export const MIN_LASTNAME = 2;
export const MAX_LASTNAME= 12;
export const COUNT_THREADS_LANDINGPAGE = 3;